### ISSUE TITLE
[Feature] Don't constantly @everyone when asking for availability 

### ISSUE THREAD

**Issue by dragid10** [dragid10/dnd-bot#1]
**Is your feature request related to a problem? Please describe.**
When asking if D&D players are available, we shouldn't use `@everyone` or `@role` unless NO ONE has responded with their availability. It makes noisy notifications and disrupts the people who have already responded

**Describe the solution you'd like**
1. If no one has responded with their availability then `@everyone` or `@role`
2. If some players have responded with availability, then specifically `@players` on the party who haven't responded
3. If everyone has responded, don't ask for the second day

**Comment by sduemler** [comment]
was going to come here to suggest this exact feature
